export const LOADING_FACILITIES = "LOADING_FACILITIES";
export const ADD_FACILITIES = "ADD_FACILITIES";
export const DELETE_FACILITIES = "DELETE_FACILITIES";
export const EDIT_FACILITIES = "EDIT_FACILITIES";

export const PRODUCT_DATA = "PRODUCT_DATA";
export const LOADING_PRODUCT = "LOADING_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const ERROR_PRODUCT = "ERROR_PRODUCT";

export const GET_SHOPDATA = "GET_SHOPDATA";
export const ADD_SHOPDATA = "ADD_SHOPDATA";
export const LOADING_SHOPDATA = "LOADING_SHOPDATA";
export const ERROR_SHOPDATA = "ERROR_SHOPDATA";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const EDIT_REVIEW = "EDIT_REVIEW";

export const ADD_CART = "ADD_CART"